all : cliente servidor

cliente : 
	cd Cliente/ && make
	cd ..

servidor : 
	cd Servidor/ && make

clean : 
	cd Cliente/ && make clean
	cd ..
	cd Servidor/ && make clean

cleanall : 
	cd Cliente/ && make cleanall
	cd ..
	cd Servidor/ && make cleanall